# Generated by Django 6.0.2 on 2026-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_transfer_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='transfer_pin',
            field=models.CharField(blank=True, help_text='Encrypted transfer PIN', max_length=255, null=True),
        ),
    ]
