# Generated by Django 6.0.2 on 2026-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_has_set_transfer_pin_user_transfer_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_deposit',
            field=models.BooleanField(default=False, help_text='User has made initial deposit'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_basic',
            field=models.BooleanField(default=True, help_text='Basic account tier'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False, help_text='Business account features'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium tier with higher limits'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_prime',
            field=models.BooleanField(default=False, help_text='Tier 0 - Bypasses all checks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Basic email/phone verification'),
        ),
    ]
