# Generated by Django 6.0.2 on 2026-02-13 16:02

from django.db import migrations
from django.contrib.auth.hashers import make_password
import random


def update_account_numbers_and_pins(apps, schema_editor):
    """Update existing users with new 10-digit account numbers and default PIN 1234"""
    User = apps.get_model('accounts', 'User')
    
    used_numbers = set()
    
    for user in User.objects.all():
        # Generate new 10-digit account number if current one is not 10 digits
        if not user.account_number or len(user.account_number) != 10 or not user.account_number.isdigit():
            while True:
                new_account_num = str(random.randint(1000000000, 9999999999))
                if new_account_num not in used_numbers:
                    used_numbers.add(new_account_num)
                    user.account_number = new_account_num
                    break
        else:
            used_numbers.add(user.account_number)
        
        # Set default transfer PIN if not already set
        if not user.transfer_pin:
            user.transfer_pin = make_password('1234')
            user.has_set_transfer_pin = True
        
        user.save(update_fields=['account_number', 'transfer_pin', 'has_set_transfer_pin'])


def reverse_migration(apps, schema_editor):
    """Reverse migration - this is a data migration so reversal is not practical"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_has_deposit_user_is_basic_user_is_business_and_more'),
    ]

    operations = [
        migrations.RunPython(update_account_numbers_and_pins, reverse_migration),
    ]
