# Generated by Django 6.0.2 on 2026-02-13 16:05

from django.db import migrations


def convert_hashed_pins_to_plaintext(apps, schema_editor):
    """Convert all hashed transfer PINs to plain text '1234'"""
    User = apps.get_model('accounts', 'User')
    
    # Update all users to have plain text PIN '1234'
    updated_count = User.objects.filter(transfer_pin__isnull=False).update(transfer_pin='1234')
    print(f"Updated {updated_count} users with plain text PIN '1234'")


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert back to hashed (though we lose original PINs)"""
    from django.contrib.auth.hashers import make_password
    User = apps.get_model('accounts', 'User')
    
    for user in User.objects.filter(transfer_pin='1234'):
        user.transfer_pin = make_password('1234')
        user.save(update_fields=['transfer_pin'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20260213_0802'),
    ]

    operations = [
        migrations.RunPython(convert_hashed_pins_to_plaintext, reverse_migration),
    ]
