# Generated by Django 6.0.2 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20260213_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code for wire transfers', max_length=20, null=True, unique=True),
        ),
    ]
