# Generated by Django 6.0.2 on 2026-03-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_ifsc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ifsc_verified',
            field=models.BooleanField(default=False, help_text="Admin has verified the user's IFSC code"),
        ),
    ]
