# Generated by Django 6.0.2 on 2026-02-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRANSACTION', 'Transaction'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('PROMOTION', 'Promotion'), ('WELCOME', 'Welcome'), ('ACCOUNT', 'Account')], default='SYSTEM', max_length=20),
        ),
    ]
